config/routes.rb
ResizeimageOrg::Application.routes.draw do
  root :to => "resizable_images#new"

  resources :resizable_images do
    member do
      get :advanced_edit, :download, :crop, :email
      put :advanced_update, :crop_update
      post :send_email 
    end
  end  

  match '/about', :to => 'about#index', :as => 'about'
  
  match ':controller/:action/:id'
  match ':controller/:action/:id.:format'

end

app/models/resizable_image.rb
class ResizableImage < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper
  attr_accessor :message, :from_email, :recipients, :x1, :y1, :x2, :y2
  attr_accessible :message, :from_email, :recipients, :image, :x1, :y1, :x2, :y2
  scope :since, lambda {|time| {:conditions => ["created_at > ?", time] }}
  after_update :reprocess_image, :if => :cropping_or_resizing?


  has_attached_file :image, :styles => {:original => "yeah!" },  :processors => [:resizer] 

  #has_attachment :content_type => :image, 
  #               :storage => :file_system, 
  #               :path_prefix => 'public/system',
  #               :max_size => 5.megabytes,
  #               :processor => :MiniMagick
 
  #validates_as_attachment

  def self.destroy_old_images
    ResizableImage.since(1.week.ago).each { |r| r.destroy }
  end
  
  def human_size
    number_to_human_size(image_file_size)
  end
  
  def to_simple_json
    self.to_json(:only => [:height, :width], :methods => [:url, :human_size])  
  end

  def url
    image.url
  end

  def cropping?
    !x1.blank? && !y1.blank? && !x2.blank? && !y2.blank?
  end

  def resizing?
    !width.blank? && !height.blank?
  end

  def cropping_or_resizing?
    cropping? || resizing? 
  end

  private
  def reprocess_image
    puts "cropping? = #{cropping?}"
    puts "resizing? = #{resizing?}"
  
    image.reprocess!

  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  caches_page :index

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/resizable_images_controller.rb
class ResizableImagesController < ApplicationController
  before_filter :load_image, :except => [ :create, :new ]
  before_filter :update_image, :only => [ :update, :advanced_update ]
  protect_from_forgery :except => [ :create ]  
  caches_page :new   

  def create
    @image = ResizableImage.new(params[:image])
    if @image.save
      flash[:notice] = 'Image was successfully created.'
      redirect_to @image      
    else
      render :action => :new
    end
  end

  def new
    @image = ResizableImage.new
    render(:layout => "application")
  end

  def show
    respond_to do |format|
      format.html 
      format.js   { render :json => @image.to_simple_json }
    end  
  end

  def update
    respond_to do |format|
      format.html { redirect_to resizable_image_path(@image) }
      format.js   { render :json => @image.to_simple_json }
    end  
  end

  def advanced_update
    respond_to do |format|
      format.html { redirect_to advanced_edit_resizable_image_path(@image) }
      format.js   { render :json => @image.to_simple_json }
    end 
  end

  def download
    send_file @image.image.path 
  end

  def crop_update
    #@image.with_image { |raw_image| @image.crop_image(raw_image, params[:x1].to_i, params[:y1].to_i, params[:x2].to_i, params[:y2].to_i) }
    @image.update_attributes(params[:resizable_image]) 
    #@image.save

    respond_to do |format|
      format.html { redirect_to crop_resizable_image_path(@image) }
      format.js   { render 'crop', :layout => false }
    end 
  end

  def send_email
    #message = EmailMessage.new(params[:email_message])
    p = ResizableImage.new(params[:image])
    mail = ImageMailer.mail_image(@image, p.message, p.from_email, p.recipients).deliver
    flash[:notice] = 'Email was successfully sent.'

    respond_to do |format|
      format.html { redirect_to @image }
      format.js   { render :json => @image.to_simple_json }
    end 
    
  rescue
    flash[:error] = 'Email was unable to send.'
    redirect_to email_resizable_image_path(@image)
  end

private 

  def load_image
    @image = params[:filename] ? ResizableImage.find_by_filename(params[:filename]) : ResizableImage.find(params[:id])
  end

  def update_image
    @image.width = params[:x]
    @image.height = params[:y]
    @image.save
    #@image.with_image { |raw_image| @image.resize_image(raw_image, [params[:x].to_i, params[:y].to_i]) }
    #@image.save
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resizable_images_helper.rb
module ResizableImagesHelper
  def resizable_image_tag(public_path, alt)
    t = Time.now.to_i
    "<img src='#{public_path}?#{t}' id='user' class='resizable' alt=#{alt} />" + hidden_tag(public_path, t)
  end
  
  def basic_image_tag(public_path, alt)
    helper_image_tag(public_path, alt, 'user')
  end

  def crop_image_tag(public_path, alt)
    helper_image_tag(public_path, alt, 'crop')
  end
  
  private
  
  def helper_image_tag(public_path, alt, id)
    t = Time.now.to_i
    "<img src='#{public_path}?#{t}' id='#{id}' alt='#{alt}' />" + hidden_tag(public_path, t)
  end
  
  def hidden_tag(public_path, time)
    "<img src='#{public_path}?#{time}' id='hidden' alt='avert your eyes!' />"
  end
end

app/views/about/index.html.erb
<div id="content">    
  <h1>About ResizeImage</h1>
  <p>Images uploaded are hosted on the server for one week. Feel free to link to your image during this period.</p>
  
  <p>Should you decide to send an email to a friend you'll be glad to know that we do not store your email address or friends' email addresses.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'resizable_images/inner_head' %>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults, 'jquery-ui', 'jquery.form', 'jcrop' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <%= render 'resizable_images/header' %>
    <%= yield %>
    <%= render 'resizable_images/footer' %>
  </div>
  <%= render 'resizable_images/analytics' %> 
</body>
</html>

app/views/layouts/resizable_images.html.erb
<!DOCTYPE html>
<html> 
<head> 
  <%= render(:partial => "inner_head")%>
  <%= stylesheet_link_tag 'jquery-ui', 'style', 'jcrop' %> 
  <script type="text/javascript" charset="utf-8" src="http://bit.ly/javascript-api.js?version=latest&amp;login=agaskell&amp;apiKey=R_93bb96e4ae3bbe9ef9a3bbde9259735f"></script>
  <script type="text/javascript" charset="utf-8" src="http://s.bit.ly/TweetAndTrack.js?v=1.01"></script>
  <%= javascript_include_tag :defaults, 'jquery-ui', 'jquery.form', 'jcrop' %>
  <meta name="medium" content="image" />
  <link rel="image_src" href="http://resizeimage.org<%= @image.image.url %>" />  
</head> 
<body>
  <div id="container">
    <%= render(:partial => "header")%>

    <div id="left_container">
      <div id="leftnav">
        <h3>Options</h3>
        <ul id="menu">
          <li><%= link_to "Start over", root_path %></li>
          <li><%= link_to "Basic resize", resizable_image_path %></li>
          <li><%= link_to "Advanced resize", advanced_edit_resizable_image_path %></li>
          <li><%= link_to "Crop", crop_resizable_image_path %></li>
        </ul>
      </div>

      <div id="left_info">
        <h3>Current Image</h3>
        
        <ul id="info">
          <li>Width: <label id="width"></label></li>        
          <li>Height: <label id="height"></label></li>        
          <li><%= link_to "Download Image", download_resizable_image_path %></li>
          <li>File size: <label id="filesize"><a href="#"><%= @image.human_size %></a></label></li>        
        </ul>
        <div id="filesizeinfo" >This is the file size as it exists on our server. Click <strong>Save changes</strong> to get the latest file size.</div>
        <div id="side_ad">
       
        </div>
      </div>
      
      <div id="share">
        <h3>Share</h3>
        <ul id="share_list">
<!--          <li><%= link_to "Email This Image", email_resizable_image_path %></li> -->
          <li><a href="#" onclick="return TweetAndTrack.open(this, '<%= resizable_image_path(:only_path => false) %>');"><span style="display:none;">I just resized my picture at http://resizeimage.org!</span>Tweet This!</a></li>
          <li><a href="http://www.facebook.com/share.php?u=<%= resizable_image_path(:only_path => false) %>">Share on Facebook</a></li>
        </ul>      
      </div>
    <!--  
      <div id="sponsor" style="height:600px;">
        <h3>Sponsors</h3>
          <script type="text/javascript"><!--
          google_ad_client = "ca-pub-9204152224485684";
          /* resizeimage */
          google_ad_slot = "9927810514";
          google_ad_width = 160;
          google_ad_height = 600;
          //-->
          </script>
          <script type="text/javascript"
          src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
          </script>
      </div> 
    </div> -->
    
    <div id="content">    
      <%= yield %> 
    </div>
    <%= render(:partial => "footer")%>
  </div>    
  <%= render(:partial => "analytics")%>

</body> 
</html> 

app/views/resizable_images/_analytics.html.erb
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-582467-6");
pageTracker._trackPageview();
</script>

app/views/resizable_images/_footer.html.erb
<div id="footer"><p>&copy; <%= Date.today.year %>  &nbsp;|&nbsp;<%= link_to "About", about_path %></p></div>

app/views/resizable_images/_form.html.erb
<%= form_for(@resizable_image) do |f| %>
  <% if @resizable_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resizable_image.errors.count, "error") %> prohibited this resizable_image from being saved:</h2>

      <ul>
      <% @resizable_image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resizable_images/_header.html.erb
<div id="header">
  <%= image_tag("logo.png", :alt => "resizeimage.org - resize pictures online for free")  %>
  <div id="top-ad"> 
  <script type="text/javascript"><!--
    google_ad_client = "ca-pub-9204152224485684";
    /* header */
    google_ad_slot = "0084059523";
    google_ad_width = 728;
    google_ad_height = 90;
    //-->
    </script>
    <script type="text/javascript"
    src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
  </script>
  </div>
</div>

app/views/resizable_images/_inner_head.html.erb
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<meta name="title" content="resizeimage.org - resize images easily." />
<meta name="description" content="resizeimage.org lets you resize images or crop your images quickly. Our staff of untrained monkeys use only the finest computing devices." />
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
<title>resizeimage.org - Resize images with ease</title>

app/views/resizable_images/advanced_edit.html.erb
<h1>Resize your image</h1>

<%= form_for @image, :url => advanced_update_resizable_image_path, :html => {:id => 'edit_form', :method => :put } do |f| %>
<div><input type="checkbox" id="preserve_ratio" checked="checked" /><label for="preserve_ratio">Keep height and width proportional</label></div>
<div><%= submit_tag "Save changes" %></div>

<div id="image_container">
<%=raw resizable_image_tag(@image.url, @image.image_file_name) %>

<input type="hidden" name="x" id="x" />
<input type="hidden" name="y" id="y" />
</div>

<% end %>

app/views/resizable_images/crop.html.erb
<h1>Crop your image</h1>

<%= form_for @image, :url => crop_update_resizable_image_path, :html => {:id => 'crop_form', :method => :put } do |f| %>

<div>
  <h3>Cropping ratio</h3>
  <input type="radio" name="ratio" value="same" id="same" /><label for="same">Same as picture</label>
  <input type="radio" name="ratio" value="square" id="square" /><label for="square">Square</label>
  <input type="radio" name="ratio" value="free" id="free" /><label for="free">Free form</label>
</div>
<div><%= submit_tag "Save changes" %></div>

<div id="image_container">
  <%=raw crop_image_tag(@image.image.url, @image.image_file_name) %>

  <%= f.hidden_field :x1, :id => :x1 %>
  <%= f.hidden_field :x2, :id => :x2 %>
  <%= f.hidden_field :y1, :id => :y1 %>
  <%= f.hidden_field :y2, :id => :y2 %>
  
</div>

<% end %>

app/views/resizable_images/edit.html.erb
<h1>Editing resizable_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @resizable_image %> |
<%= link_to 'Back', resizable_images_path %>

app/views/resizable_images/index.html.erb
<h1>Listing resizable_images</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resizable_images.each do |resizable_image| %>
  <tr>
    <td><%= link_to 'Show', resizable_image %></td>
    <td><%= link_to 'Edit', edit_resizable_image_path(resizable_image) %></td>
    <td><%= link_to 'Destroy', resizable_image, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resizable image', new_resizable_image_path %>

app/views/resizable_images/new.html.erb
<%= form_for :image, :url => resizable_images_path, :html => {:id => 'image_form', :multipart => true} do |f| %>
<div id="file">
<%= label(:image, "Select an image") %><%= f.file_field :image %>
</div>
<%= submit_tag "Upload Image" %>
<% end %>

app/views/resizable_images/show.html.erb
<h1>Resize your image</h1>

<%= form_for @image, :html => {:id => 'edit_form', :method => :put } do |f| %>

<div id="options">
  <input type="radio" name="size" value=".3" id="small" /><label for="small">Small</label>
  <input type="radio" name="size" value=".5" id="medium" /><label for="medium">Medium</label>
  <input type="radio" name="size" value=".7" id="large" /><label for="large">Large</label>
  <input type="radio" name="size" value="1" id="original" /><label for="original">Original</label>
  
  <span>Want a custom size? Try our <%= link_to "advanced editor", advanced_edit_resizable_image_path %></span>
</div>
<div><%= submit_tag "Save changes" %></div>

<div id="image_container">
<%=raw basic_image_tag(@image.image.url, @image.image_file_name) %>


<input type="hidden" name="x" id="x" />
<input type="hidden" name="y" id="y" />
</div>

<% end %>